### ISSUE TITLE
Mask-rcnn paddle需要加入一个环境变量才可以最大bs=5的问题

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/benchmark#40]
mask-rcnn paddle最大bs=5测试需要加入环境变量
FLAGS_limit_of_tmp_allocation=2147483648
这个对用户相当不友好，需要优化一下，
加入该环境变量后，会导致速度从0.344 s/step 下降到 0.347 s/step

**Comment by Xreki** [comment]
`2147483648`这个值怎么来的啊

**Comment by ccmeteorljh** [comment]
最新环境变量已更新是：FLAGS_conv_workspace_size_limit=1500

**Comment by sneaxiy** [comment]
`FLAGS_conv_workspace_size_limit`用于限制cudnn workspace大小。如果不设置该环境变量，在bs=5时Mask RCNN cudnn workspace占了3G显存，严重影响显存性能。
